name: JSON Validation

on:
  push:
    paths:
      - '**/*.json'
  pull_request:
    paths:
      - '**/*.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get changed JSON files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: '**/*.json'

      - name: Validate JSON syntax with jq
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "checking json syntax"
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n'

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if ! jq empty "$file"; then
              echo "invalid json: $file"
              exit 1
            fi
          done

      - name: Check for trailing commas
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "checking for trailing commas"
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n'

          fail=0
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if grep -n -E ',\s*[\}\]]' "$file"; then
              echo "trailing comma found in $file"
              fail=1
            fi
          done

          if [ "$fail" -eq 1 ]; then
            echo "remove trailing commas before commit"
            exit 1
          fi
